FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /build/Samples/DecoderSample/
COPY ./Samples/DecoderSample ./

#RUN dotnet restore --ignore-failed-sources
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0-bullseye-slim AS runtime
WORKDIR /app
COPY --from=build-env /build/Samples/DecoderSample/out/* ./
ENTRYPOINT ["dotnet", "SensorDecoderModule.dll"]
